version: 2
jobs:
  Critical_Path_Test_Staging:
    docker:
      - image: circleci/openjdk:8u232-jdk-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Run Critical Path Tests
          command: |
            mvn clean verify -Dcucumber.options="--tags @smoke" -Dbrowser.instances=1

workflows:
  version: 2
  master-changed:
    jobs:
      - Critical_Path_Test_Staging:
          filters:
            branches:
              only:
                - master