version: 2

jobs:
  Critical_Path_Test_Staging:
    docker:
      - image: circleci/openjdk:8u232-jdk-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Run Critical Path Tests
          command: mvn clean verify -q -Dcucumber.options="--tags @smoke" -Dbrowser.instances=1
      - run:
          name: Save test results
            command: |
              mkdir -p ~/test-results/junit/
              find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
            when: always

      - store_test_results:
          path: ./target/surefire-reports/testng-results.xml

      - store_artifacts:
          path: ./target/surefire-reports/

workflows:
  version: 2
  master-changed:
    jobs:
      - Critical_Path_Test_Staging:
          filters:
            branches:
              only:
                - master
