version: 2

jobs:
  Critical_Path_Test_Staging:
    docker:
      - image: circleci/openjdk:8u232-jdk-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Run Critical Path Tests
          command: |
            set -e
            mvn clean verify -q -Dcucumber.options="--tags @circle" -Dbrowser.instances=1
      - run:
          name: Save test results
          command: |
            set -e
            mkdir ./test-results
            cp ./target/surefire-reports/testng-results.xml ./test-results
          when: always

      - store_test_results:
          path: ./test-results

workflows:
  version: 2
  master-changed:
    jobs:
      - Critical_Path_Test_Staging:
          filters:
            branches:
              only:
                - master
